version: "2"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/ChessService
    ports:
      - "5000:3000"
    depends_on:
      - db
  app:
    build: ./UsersPostsComments/Service
    image: tautvis/service
    working_dir: /UsersPostsComments/Service
    volumes:
      - ./UsersPostsComments/Service:/Service
      - ~/UsersPostsComments/.m2:/root/.m2
    ports:
      - "80:80"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: WebServicesPostsService
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    container_name: mysql-standalone
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

