# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7ec6a4ae6f3120e178637335d0fe2688e6cad082a77b90fa2a5a7ce5e4c4133b488f580b31e76acb344606ee3c24057b0e1149c00d2b6d3967a81e8f7f401d9

test:
  secret_key_base: e472de5a547c7fa52032d26e9d09c2ef0a26ba55572d098e4397765f10d0538f3f7d29b31af0216fc38b84b863dbb014bf86debbcda5c4d70e661c6552536881

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
